# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5Hash', models.CharField(max_length=32)),
                ('video', models.CharField(max_length=11)),
            ],
        ),
    ]
