# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naomiselector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='md5Hash',
            new_name='md5hash',
        ),
    ]
