# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naomiselector', '0002_auto_20160826_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='md5hash',
            new_name='hash',
        ),
    ]
